[[customizations.user]]
name = "ansible"
key = ""
groups = ["wheel"]

[[customizations.user]]
name = "root"
key = ""

[customizations.kernel]
append = "console=ttyS0,115200 console=tty0"

[customizations.services]
enabled = ["sshd", "NetworkManager", "chronyd", "lldpd"]

[customizations.timezone]
timezone = "UTC"

[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "us"
