all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_host: 127.0.0.1
      ansible_user: ansible
  children:
    baremetal:
      hosts:
        home380a:
          ansible_connection: ssh
          bmc_address: "10.9.1.51"
          bmc_username: "Administrator"
          bmc_password: "password1"
          bmc_type: "redfish"
      vars:
        # Network testing variables
        test_vlans: [ 10, 20, 30, 100, 200 ]
        test_subnets:
        - "10.9.1.0/24"
        - "10.9.2.0/24"
        - "192.168.1.0/24"
        - "10.0.0.0/24"
        - "172.16.0.0/24"
        # LACP testing variables
        lacp_modes:
        - "802.3ad"
        - "active-backup"
        - "balance-xor"
        lacp_rates: [ "slow", "fast" ]

        # Hardware enumeration variables
        hardware_scan_enabled: true
        firmware_update_enabled: false

        # Reporting variables
        controller_ip: "{{ ansible_env.CONTROLLER_IP | default('') }}"
        report_to_controller: true
